# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

COPY package.json package-lock.json tsconfig.json ./

RUN npm install --ignore-scripts --no-audit --no-fund

COPY . .

RUN npm run build

ENV NODE_ENV=production

ENTRYPOINT ["node", "build/index.js"]
